services:
  mongodb:
    image: mongo
    profiles:
      - prod
      - dev
    restart: always
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: food_order_user
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: food_order
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - food-order-network

  food-order:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-order-BE
    ports:
      - 3000:3000
    profiles:
    - prod
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always
    networks:
      - food-order-network

networks:
  food-order-network:
    driver: bridge

volumes:
  mongodb_data:
